name: Main Tests

on:
  push:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout the triggered branch from the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: installing Cypress dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start Node Express Server on background
        run: nohup npm start > /dev/null 2>&1 &
      - name: Unit tests
        run: npm test
      - name: E2E tests
        run: npm run e2e
        env:
          LANG: ja_JP.UTF-8


