name: Main Tests

on:
  push:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout the triggered branch from the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        env:
          RUNNER_TEMP: /tmp
        with:
          node-version: 12
      - name: Install all npm packages
        run: npm run install-all
      - name: Unit tests
        run: npm test

